//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedules
    {
        public int Id { get; set; }
        public string FirstTeam { get; set; }
        public string SecondTeam { get; set; }
        public System.TimeSpan Date { get; set; }
        public int ResultsId { get; set; }
        public int TeamsId { get; set; }
    
        public virtual Teams Team { get; set; }
        public virtual Results Result { get; set; }
    }
}
